### ISSUE TITLE
[Bug] vue-datepicker-ui@vue3 isn't supported by any available resolver

### ISSUE THREAD

**Issue by BudiSalah** [edisdev/vue-datepicker-ui#56]
## The Issue

When I try to install the package via `yarn`, it aborts with the following message:

```
YN0000: ┌ Resolution step
➤ YN0001: │ Error: vue-datepicker-ui@vue3 isn't supported by any available resolver
    at yf.getResolverByDescriptor (C:\Users\[user-name]\AppData\Local\Volta\tools\image\yarn\3.4.0\bin\yarn.js:391:1647)
    at yf.bindDescriptor (C:\Users\[user-name]\AppData\Local\Volta\tools\image\yarn\3.4.0\bin\yarn.js:391:1036)   
    at Z (C:\Users\[user-name]\AppData\Local\Volta\tools\image\yarn\3.4.0\bin\yarn.js:439:6900)
➤ YN0000: └ Completed
➤ YN0000: Failed with errors in 0s 48ms
```

## Used tools

- `yarn` v3.4.0
- `node` v16.0.0

**Comment by BudiSalah** [comment]
I fixed this issue by running `yarn add vue-datepicker-ui@3.1.1`
