### ISSUE TITLE
SyntaxError: Unexpected token <

### ISSUE THREAD

**Issue by sokolovdm** [edisdev/vue-datepicker-ui#6]
Hello. When i adding import Calendar from 'vue-datepicker-ui' prooject crushs with this error

/Library/WebServer/projects/finaxe/node_modules/vue-datepicker-ui/src/components/calendar.vue:1
(function (exports, require, module, __filename, __dirname) { <template>
                                                                                                        ^
SyntaxError: Unexpected token <
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:617:28)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at r (/Library/WebServer/projects/finaxe/node_modules/vue-server-renderer/build.js:8341:16)
    at Object.vue-datepicker-ui (webpack:/external "vue-datepicker-ui":1:0)
    at __webpack_require__ (webpack/bootstrap:19:0)
    at Module../node_modules/babel-loader/lib/index.js!./node_modules/vue-loader/lib/index.js?!./src/components/blanks/RangeTime.vue?vue&type=script&lang=js& (server-bundle.js:2718:75)
    at __webpack_require__ (webpack/bootstrap:19:0)
    at Module../src/components/blanks/RangeTime.vue?vue&type=script&lang=js& (server-bundle.js:13828:192)
    at __webpack_require__ (webpack/bootstrap:19:0)

**Comment by edisdev** [comment]
Hi, I'm sorry for the late reply 🙏  Does this problem persist?

**Comment by edisdev** [comment]
@sokolovdm  Hello  👋  Can you try latest version ?
